import { CourseResponse } from './CourseResponse';
import { GroupResponse } from './GroupResponse';
import { UserResponseShort } from './UserResponseShort';

export interface GroupResponseById {
  // students: {    id: number;
  //   firstName: string;
  //   lastName: string;
  //   email: string;
  //   photo: string; }[];
  // teachers:{    id: number;
  //   firstName: string;
  //   lastName: string;
  //   email: string;
  //   photo: string; }[];
  // tutors: {    id: number;
  //   firstName: string;
  //   lastName: string;
  //   email: string;
  //   photo: string; }[];
  //   id: number;
  //   name: string;
  //   course: CourseResponse;
  //   groupStatus: string;
  //   startDate: string;
  //   endDate: string;
  //   timetable: string;
  //   paymentPerMonth: number;
  students: UserResponseShort[];
  teachers: UserResponseShort[];
  tutors: UserResponseShort[];
  id: number;
  name: string;
  course: CourseResponse;
  groupStatus: string;
  startDate: string;
  endDate: string;
  timetable: string;
  paymentPerMonth: number;
}
